themes:
  grid:
    tile_size: 160
  duotone:
    palettes:
      PURPLISH: [ '#16006F', '#F7396F' ]
      NATURAL: [ '#1A2A56', '#00D574' ]
      DIVERGENT: [ '#7a004f', '#80f8f8' ]
      SUN: [ '#EA1264', '#D7FD31' ]
      YELLISH: [ '#141209', '#ffea00' ]
      HORROR: [ '#131313', '#B71C1C' ]
      SEA: [ '#0239d8', '#68ebc1' ]
      REWIND2020: [ '#000000', '#FD0F57' ]
      PINK: ['#EE0D92', '#FFBADF']
      NEON: [ '#732fd0', '#44ff94' ]
      MUSICORUM: ['#131313', '#B71C1C']

#result_url: https://result.musicorumapp.com/
#result_url: http://localhost:8000/
result_url: http://localhost:5000/
#result_url: file:///D:/Projects/Musicorum/share/export/

resource_url: https://resource.musicorumapp.com/

auth:
  twitter:
    callback: http://localhost:4030/auth/social/twitter
